# -*- coding: utf-8 -*-
"""Laboratorio#1-AndrésCabezasVizcaíno.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bylRrYLjZmifJqlpdkKIwJ_XpS0jMKK5
"""

print("Ejercicio #1 Calcular Distancia ")
print("Ingrese la velocidad y el tiempo de la unidad movil")
v=float(input("Ingrese la velocidad:"))
t = float(input("Ingrese el tiempo:"))
print("La distancia es:"+str(v*t))

print("Ejercicio #2 Promedio notas")
nota1 = float(input("Ingrese la nota 1:"))
nota2 = float(input("Ingrese la nota 2:"))
nota3 = float(input("Ingrese la nota 3:"))
print("El promedio de las notas es: "+str((nota1+nota2+nota3)/3))

#Se necesita elaborar un algoritmo que solicite el numero de respuestas correctas, incorrectas y en blanco,
#correspondientes a postulantes, y muestre su puntaje final considerando que por cada respuesta correcta 
#tendrá  3 puntos, respuestas incorrectas tendrá -1 y respuestas en blanco tendrá 0

correctas = int(input("Ingrese el número de respuestas correctas: "))
incorrectas = int(input("Ingrese el número de respuestas incorrectas: "))
en_blanco = int(input("Ingrese el número de respuestas en blanco: "))

puntaje = (correctas * 3) + (incorrectas * -1) + (en_blanco * 0)

print("El puntaje final del postulante es:", puntaje)